import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import AssetBrowser from "../components/AssetBrowser";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Wartable</h1>
        <h2>Asset Manager</h2>
        <button
          onClick={() => {
            window.alert("New Asset");
          }}
        >
          New Asset
        </button>
        <AssetBrowser />
      </main>
    </div>
  );
};

export default Home;
