import type { NextPage } from "next";
import Head from "next/head";
import { getAssets, newS3Client } from "../api/s3";
import AssetBrowser from "../components/AssetBrowser";
import useSTLManager from "../hooks/useSTLManager";
import styles from "../styles/Home.module.css";
import { Asset } from "../types";

type Props = {
  assets: Asset[];
};

const Home: NextPage<Props> = ({ assets }) => {
  const { loadedGeometries, hasLoaded } = useSTLManager(assets);


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Wartable</h1>
        <h2>Asset Manager</h2>
        <button
          onClick={() => {
            window.alert("New Asset");
          }}
        >
          New Asset
        </button>
        <AssetBrowser assets={assets} loadedGeometries={loadedGeometries}/>
      </main>
    </div>
  );
};

export default Home;

export const getStaticProps = async () => {
  const client = newS3Client();

  const assets = await getAssets(client);

  return {
    props: {
      assets,
    },
  };
};
